# Generated by Django 4.1.3 on 2022-11-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('numero_residencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_dueno', models.CharField(max_length=50)),
                ('fono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('conserje', models.CharField(max_length=50)),
                ('remitente', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Elige una opción', 'Elige una opción'), ('Entregado', 'Entregado'), ('No entregado', 'No entregado')], default='Elige una opción', max_length=20)),
                ('numero_residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
            ],
        ),
    ]
